import './globals.css'
import Header from '@/components/Header'
import local from 'next/font/local'
import localFont from 'next/font/local'

export const metadata = {
  title: 'Mockify',
  description: 'Generated by create next app',
}

const neue = localFont({ 
  src: './localfont/HelveticaNeueLTPro-Roman.7216551.woff2',
  formats: ['woff2'],
  // fontWeight: 'normal',
  variable: "--font-neue",
  fontDisplay: 'swap', 
})
const Ppe = localFont({ 
  src: './localfont/PPEditorialNew-Regular.2512cb3.woff2',
  formats: ['woff2'],
  // fontWeight: 'normal',
  variable: "--font-ppe",
  fontDisplay: 'swap', 
})
const ppe_italic = localFont({
  src: './localfont/PPEditorialNew-Italic.1d7842d.woff2',
  formats: ['woff2'],
  variable: "--ppe_italic"
})


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Header />
        <main className={`${Ppe.variable} ${neue.variable} ${ppe_italic.variable}`}>
        {children}
        </main>
        </body>
    </html>
  )
}
